### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by Vani177** [nitishhsinghhh/Tips-and-Tricks-Programming-using-Cpp#1]
Hey! 
I've noticed the LICENSE.md file has not been created in the repository yet. 
I would like to contribute to the repository by adding the file. 
Please assign me this issue.

**Comment by nitishhsinghhh** [comment]
You have been invited as a collaborator, please accept the invitation so that I can assign you tasks and you can contribute to the repository.

**Comment by Vani177** [comment]
Sure, thanks!

**Comment by Vani177** [comment]
hey @nitishhsinghhh 
are you back?
